version: '3'

services:
  couchdb:
    image: couchdb:2.3.1
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: "pA%sw0rd"

  mongodb:
    image: mongo:4.4.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "pA%sw0rd"
    ports:
      - 27017:27017
  mongo-express:
      image: mongo-express
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: "pA%sw0rd"
        ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on:
        - mongodb

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "pA%sw0rd"

  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "pA%sw0rd"

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pA%sw0rd"
