version: '3'

services:
  couchdb:
    image: couchdb:2.3.1
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: "1234"
  mongodb:
    image: mongo:4.4.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "1234"
    ports:
      - 27017:27017
