apiVersion: v1
kind: Secret
metadata:
  name: external-database-secrets
  namespace: external-database-operator-system
type: Opaque
stringData:
  mysqlHost: "my-dbs-system.tld"
  mysqlAdminUsername: "root"
  mysqlAdminPassword: ""
  couchdbUrl: ""
  couchdbAdminUsername: "root"
  couchdbAdminPassword: ""
  mongoUrl: "mongodb://root:iwonttellyou@my-dbs-system.tld:27017/?authSource=admin"